- .circleci/config.yml
- README.md
- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/2737.
> adds Circle CI config for initial builds

- helmclient.go
- spec.go
> Rename InstallTiller EnsureTillerInstalled and add early check+return

- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/3093
> Show error stack on retry failure

- spec.go
Towards https://github.com/giantswarm/adidas/issues/307
> use gs image for tiller

- helmclient.go
Addresses feedback from https://github.com/giantswarm/helmclient/pull/34.
> Use constant for timeout when running tests

- Gopkg.lock
- integration/test/basic/main_test.go
- vendor/github.com/giantswarm/e2e-harness/pkg/framework/host.go
Not needed due to https://github.com/giantswarm/e2e-harness/pull/114 ❤️
> Remove setting target namespace

- helmclient.go
Fixes https://github.com/giantswarm/giantswarm/issues/4195.
> adds backoff for tiller deployment installation

- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/4059
> fix tiller not retry found handling

- helmclient.go
Error handling was applied to wrong call.
> fix IsTillerNotFound handling

- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/4481.
Follow up of https://github.com/giantswarm/helmclient/pull/53#discussion_r227358652.
> helmclient: don't handle IsReleaseNotFound during installing release

- helmclient.go
- helmclient_test.go
- spec.go
Towards https://github.com/giantswarm/giantswarm/issues/4326
> Adds ListReleaseContents

- error.go
- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/4809
This is prep for updating the tiller pod. Adds `getTillerImage` which will be used to check if the image is outdated.
> Add getTillerImage

- .circleci/config.yml
- integration/setup/config.go
- integration/setup/setup.go
- integration/test/upgradetiller/error.go
- integration/test/upgradetiller/main_test.go
- integration/test/upgradetiller/project.yaml
- integration/test/upgradetiller/upgrade_tiller_test.go
Towards https://github.com/giantswarm/giantswarm/issues/4809
Adds structure for new e2e test for the upgrade process.
> Add structure for upgrade tiller e2e test

- helmclient.go
- helmclient_test.go
- integration/test/upgradetiller/upgrade_tiller_test.go
- spec.go
Note: this is change proposal to #71.
> upgrade-tiller changes

- helmclient.go
- helmclienttest/helmclient.go
- spec.go
Required to augment the tiller deployment and add priorityclasses, tolerations etc pp.
> Add value input to tiller installer

- helmclient.go
- helmclient_test.go
- types.go
Toward: https://github.com/giantswarm/giantswarm/issues/5751
After this, I would need to update `chartstatus` resource.
> Add new description field for status update

- ensure_tiller_installed.go
- error.go
- helmclient.go
- helmclient_test.go
Toward: https://github.com/giantswarm/giantswarm/issues/6157
> Resulting upper tiller version into lower desired version

- integration/test/upgradetiller/upgrade_tiller_test.go
- spec.go
Toward https://github.com/giantswarm/giantswarm/issues/6157
> Tiller upgrade to v2.14.1

- ensure_tiller_installed.go
towards giantswarm/giantswarm/issues/6013
> Tiller PSP

- ensure_tiller_installed.go
Towards: giantswarm/giantswarm/issues/6013
Adjust psp to allow running as root and to allow escalation as this is required
> Adjust Tiller psp

- .circleci/config.yml
- integration/env/common.go
- integration/setup/config.go
- integration/test/basic/project.yaml
- integration/test/deleterelease/project.yaml
- integration/test/installrelease/project.yaml
- integration/test/upgradetiller/project.yaml
Towards giantswarm/giantswarm#4606
> Use KIND in e2e tests

- error.go
- error_internal.go
- pull_chart_tarball.go
Toward https://github.com/giantswarm/giantswarm/issues/7359
Return `Permanent` error in case of no host issue or HTTP not found.
> Return permanent error in case of tarball not found

- .circleci/config.yml
- ensure_tiller_installed.go
- error.go
- integration/test/upgradetiller/upgrade_tiller_test.go
Toward https://github.com/giantswarm/giantswarm/issues/7390
Deleting preinstall procedure for `UpgradeTillerTest` and move it circleCI config.
> Fixing e2e error cases

- README.md
Towards https://github.com/giantswarm/giantswarm/issues/7584
> Update and improve README

- error.go
- pull_chart_tarball.go
Sorting out the error handling.
> Return separate error for 404s pulling tarballs

- ensure_tiller_installed.go
Replaces #93 by @MarcelMue.
We tried adding this before but the API version was moving around. It's been stable since 1.14 so we should be good now.
https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
This helps with running chart-operator locally against an empty cluster. In production clusters the priority class is created via ignition.
> Create giantswarm-critical priorityclass for tiller

- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/8479
> Handle unavailable tenant cluster in GetReleaseContent

- error.go
- pull_chart_tarball.go
Cherry pick of https://github.com/giantswarm/helmclient/pull/155.
> helm3: Handle timeouts pulling charts and add monitoring

- error.go
- helmclient.go
Towards giantswarm/giantswarm#8479
> Don't try to create tunnel when tiller is outdated

- README.md
- error.go
> helm3: Delete tiller errors and update readme

- error.go
- helmclient.go
- helmclienttest/helmclient.go
- install.go
- integration/test/basic/basic_test.go
- integration/test/basic/fixtures/test-chart/templates/pod.yaml
- spec.go
Towards https://github.com/giantswarm/roadmap/issues/30
> helm3:  Implement InstallChartFromTarball

- get.go
- helmclienttest/helmclient.go
- integration/test/basic/basic_test.go
- spec.go
> Fix param order for GetReleaseContent

- delete.go
- get.go
- helmclient.go
- helmclienttest/helmclient.go
- history.go
- integration/test/basic/basic_test.go
- integration/test/basic/fixtures/test-chart/Chart.yaml
- spec.go
Towards https://github.com/giantswarm/roadmap/issues/30
> helm3: Implement GetReleaseHistory and DeleteRelease

- get.go
- helmclient.go
- helmclienttest/helmclient.go
- integration/test/basic/basic_test.go
- list.go
- loadchart.go
- spec.go
> helm3: Implement LoadChart and ListReleases

- CHANGELOG.md
- go.sum
- helmclient.go
- helmclient_test.go
- types.go
Towards giantswarm/giantswarm#9900
See https://github.com/giantswarm/apiextensions/pull/400#issue-400886114.
> Add revision to GetReleaseHistory

- CHANGELOG.md
> Release v0.2.2

- go.mod
- go.sum
- helmclient.go
- integration/test/basic/basic_test.go
- types.go
Getting the helm3 branch in sync with master.
> helm3: Add revision to GetReleaseContent

- .circleci/config.yml
I'll remove the env vars from helmclient settings once this is merged.
> Update orb and use architect context

- error.go
- merge_values.go
- merge_values_test.go
Same as https://github.com/giantswarm/helmclient/pull/229 but only for helmclient 0.x.x which support helm 2.
> helm2; Extending map merging errors

- .dependabot/config.yml
- .github/dependabot.yml
- .github/workflows/zz_generated.gomodtidy.yaml
auto assign team-batman-engineers for reviewing dependabot PR's
> dependabot v2

- .circleci/config.yml
- .github/workflows/zz_generated.create_release.yaml
- .github/workflows/zz_generated.create_release_pr.yaml
- CHANGELOG.md
Adding the workflows to our libraries.
> Add github workflows for release automation

- CHANGELOG.md
- install.go
- spec.go
- update.go
Towards https://github.com/giantswarm/giantswarm/issues/11735
Needed for https://github.com/giantswarm/opsctl/pull/740.
> Add timeouts for installing or updating helm releases

- CHANGELOG.md
- pkg/helmclient/delete.go
- pkg/helmclient/install.go
- pkg/helmclient/metric.go
- pkg/helmclient/rollback.go
- pkg/helmclient/update.go
Towards https://github.com/giantswarm/giantswarm/issues/13309
> Add metrics for event counts

- CHANGELOG.md
- pkg/helmclient/delete.go
- pkg/helmclient/install.go
- pkg/helmclient/metric.go
- pkg/helmclient/rollback.go
- pkg/helmclient/update.go
Toward https://github.com/giantswarm/giantswarm/issues/13535
> Adding release name as labels

- .circleci/config.yml
- CHANGELOG.md
- go.mod
- go.sum
Towards giantswarm/giantswarm#13905
> Add replace for moby v20.10.0-beta1 to fix build issue on darwin

- CHANGELOG.md
- pkg/helmclient/install.go
- pkg/helmclient/spec.go
Towards giantswarm/giantswarm#13746
> Pass SkipCRDs to helmclient

- CHANGELOG.md
- integration/test/basic/basic_test.go
- integration/test/releasetesting/release_testing_test.go
- pkg/helmclient/delete.go
- pkg/helmclient/spec.go
- pkg/helmclienttest/helmclient.go
Towards: https://github.com/giantswarm/giantswarm/issues/23699
> Adding support for timeout on deletion

- README.md
> Update README.md (change "master" to "main")

- .nancy-ignore
- pkg/helmclient/pull_chart_tarball.go
Fixes https://github.com/giantswarm/giantswarm/issues/33053
> Adapt for golangci-lint v2
