- helmclient.go
- tunnel.go
The errors being masked below cause the trace to not show the position of the masking because the maskable errors are wrapped by the `fmt` package. This PR fixes this.
> improves error handling

- backoff.go
- error.go
- helmclient.go
- helmclient_test.go
Towards https://github.com/giantswarm/giantswarm/issues/2737. While testing around I figured working against a CNR is not really reliable. Especially not when having port forwarding in between. This PR tries to harden the client by adding backoffs where necessary.
> adds backoffs everywhere

- helmclient.go
- spec.go
Just adds the method to spec.go as I noticed it was missing.
> Add InstallTiller to spec.go

- helmclient.go
We need to fall through if the first attempt to create the tunnel fails, we might actually need to install Tiller in that case.
> Do not return on tunnel creation failure during early check

- helmclient.go
- spec.go
If we try to deploy tiller on a different namespace the ServiceAccount and ClusterRolebinding might be already there for another tiller deployment, these changes prevent clashes and add logging info.
> Rename tillerPodName to avoid clashes and add logging info

- error.go
- helmclient.go
Related to https://github.com/giantswarm/giantswarm/issues/3109
This will give us more insight into the laconic `gzip: invalid header` error.
> add additional info for invalid gzip header

- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/3109
When we get an invalid gzip header failure it is usually because we are trying to install a chart from a tarball file and, because of an error condition, the file contains json error response instead of a gzipped chart. With these changes we will get the content of that json document in the error log in case of an invalid gzip header failure.
> Show returned file contents on invalid gzip header failure

- error.go
- helmclient.go
Towards https://github.com/giantswarm/cluster-operator/issues/103
This will allow us to check a Tiller installation error and stop reconciliation in that case instead of bailing out.
> Return annotated tiller installation error

- error.go
- helmclient.go
This will allow us to detect errors related to the guest API not being available and act according to that in consumer code, for instance, we may stop a reconciliation loop if we are getting this kind of error after creating a guest cluster and expect to have the API ready soon.
> Add function for asserting guest API not available errors

- error.go
This will identify transient certificate errors like:
```
Post https://api.29bxw.k8s.tarantula.germanycentral.azure.gigantic.io/api/v1/namespaces/giantswarm/serviceaccounts: x509: certificate is valid for ingress.local, not api.29bxw.k8s.tarantula.germanycentral.azure.gigantic.io
```
and
```
Get https://api.29bxw.k8s.tarantula.germanycentral.azure.gigantic.io/api/v1/namespaces/giantswarm: x509: certificate is valid for ingress.local, not api.29bxw.k8s.tarantula.germanycentral.azure.gigantic.io
```
These errors usually happen while the guest API is not fully up, once the API is responding they stop appearing. They will be returned as `guestAPINotAvailableError`, so that consumer libraries can act accordingly (for instance, canceling a reconciliation loop).
> Add more patterns to detect guest cluster API not ready

- helmclient.go
- spec.go
Towards https://github.com/giantswarm/giantswarm/issues/3925
Makes available PingTiller to external consumers of the library, this will be useful to create an alert on Tiller unreachable.
> Expose PingTiller

- helmclient.go
- spec.go
Aims to prevent an unlimited number of previous release versions to be stored. See https://gigantic.slack.com/archives/C02MS174K/p1535545641000100
> Set helm init's max history param

- error.go
- helmclient.go
... instead of meaningless pod not found.
Towards https://github.com/giantswarm/giantswarm/issues/4059.
Again this allows to build idempotent code around that function call.
> return tillerNotFound error

- README.md
It uses it in draining e2e test.
> readme: add aws-operator to dependent projects

- error.go
- helmclient.go
- helmclient_test.go
Towards https://github.com/giantswarm/giantswarm/issues/4809
Adds check for whether the tiller pod is outdated. This will be used in a later PR to trigger the upgrade process.
> Add check for tiller pod being outdated

- helmclienttest/helmclient.go
- helmclienttest/helmclient_test.go
Towards https://github.com/giantswarm/giantswarm/issues/4949
This is prep for some helmclient changes I need to make for chart-operator. Adds the helmclienttest package so we can remove the `mock_test.go` files we have in chart-operator and cluster-operator.
e.g. https://github.com/giantswarm/chart-operator/blob/1553942b22cbecea7b26b7b90bb56399d3b3d8f6/service/controller/chartconfig/v5/resource/chart/mock_test.go
> Add helmclienttest package

- helmclienttest/helmclient.go
- helmclienttest/helmclient_test.go
Same issue as with `apprclienttest`. See https://github.com/giantswarm/apprclient/pull/25.
> Don't return error in helmclienttest constructor

- DCO
- LICENSE
- README.md
- helmclient.go
- spec.go
Fixes https://github.com/giantswarm/giantswarm/issues/5010
Currently EnsureTillerInstalled always creates a cluster role binding with the name `tiller-giantswarm`. This breaks in clusters where Tiller is installed in `kube-system` and `giantswarm` e.g the front end cluster on `gollum`.
Fix is to use `tiller-[namespace]` as the name of the role binding.
> Cluster role binding name should include the namespace

- helmclient.go
- helmclient_test.go
We had a problem in `talos` because the Tiller deployment had been changed manually and didn't have a version tag `quay.io/giantswarm/tiller`. 
```
panic: [{/go/src/github.com/giantswarm/draughtsman/service/service.go:171: service.Boot} {/go/src/github.com/giantswarm/draughtsman/vendor/github.com/giantswarm/helmclient/helmclient.go:278: } {/go/src/github.com/giantswarm/draughtsman/vendor/github.com/giantswarm/helmclient/helmclient.go:863: } {/go/src/github.com/giantswarm/draughtsman/vendor/github.com/giantswarm/helmclient/helmclient.go:886: tiller image `quay.io/giantswarm/tiller` is invalid} {execution failed error}]
```
Currently we error and this causes a panic and alerts. This is to make the version check smarter. If the image tag is empty or `latest` we treat it as outdated. So the …
> Improve tiller version check when deployment has been changed manually

- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/5218
Fixes to helmclient needed for https://github.com/giantswarm/cluster-operator/pull/386. With this all chartconfig CRs and chart-operator are installed in a single reconciliation loop the first time the tenant cluster becomes available.
> Wait for tiller to be installed

- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/5224
I've seen this error `invalid state cannot both install and upgrade tiller` a few times during cluster creation when cluster-operator is bootstrapping tiller.
This fixes the current check which is just wrong. 🤦‍♂️
> Fix check when both install and upgrade tiller are true

- error.go
- helmclient.go
- pull_chart_tarball.go
Toward https://github.com/giantswarm/giantswarm/issues/5743
Only affect `InstallReleaseFromTarball` function.
> Reduce backoff exponential time & catch YAML parsing error as permanent

- Gopkg.lock
- Gopkg.toml
- merge_values.go
- merge_values_test.go
- vendor/github.com/google/go-cmp/LICENSE
- vendor/github.com/google/go-cmp/cmp/compare.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
- vendor/github.com/google/go-cmp/cmp/internal/function/func.go
- vendor/github.com/google/go-cmp/cmp/internal/value/format.go
- vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
- vendor/github.com/google/go-cmp/cmp/options.go
- vendor/github.com/google/go-cmp/cmp/path.go
- vendor/github.com/google/go-cmp/cmp/reporter.go
- vendor/github.com/google/go-cmp/cmp/unsafe_panic.go
- vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go
Towards giantswarm/giantswarm#4949
This is prep for https://github.com/giantswarm/helmclient/pull/94. In chart-operator we need to merge configmap and secret values stored as YAML.
The merge logic needs the inputs to be `map[string]interface{}` types. But go-yaml V2 returns a `map[interface{}]interface{}` . They plan to change this in go-yaml V3.
This implements a workaround suggested in the upstream issue https://github.com/go-yaml/yaml/issues/139.
> Parse yaml

- merge_values.go
- merge_values_test.go
Setting leaf or even higher level key to `null` is official way of overriding default key setting with intent to having it deleted (see [docs](https://helm.sh/docs/chart_template_guide/#deleting-a-default-key)). To be able to use `helmclient.MergeValues` in `opsctl ensure appcatalogs` command logic and have the command properly supporting customization / overrides / key deletion via `null` value, merging and processing `null` valued keys needs to be supported. This PR adds that feature.
> Support merging and processing null valued keys

- integration/test/upgradetiller/upgrade_tiller_test.go
- spec.go
This reverts commit 505b8ddcd168c0e360c766d27849fd7496e83bbb.
To update tiller, we need to update k8s version first.
> Revert "Tiller upgrade to v2.14.1 (#104)"

- ensure_tiller_installed.go
Towards https://github.com/giantswarm/giantswarm/issues/4033
Code generates policy:
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
creationTimestamp: "2019-06-19T17:06:25Z"
generation: 2
name: tiller-deploy
namespace: giantswarm
resourceVersion: "1170583"
selfLink: /apis/extensions/v1beta1/namespaces/giantswarm/networkpolicies/tiller-deploy
uid: 9258a16b-92b4-11e9-b419-000d3a44433d
spec:
egress:
- to:
- ipBlock:
cidr: 10.0.0.0/8
- ipBlock:
cidr: 172.16.0.0/12
- ipBlock:
cidr: 192.168.0.0/16
ingress:
- ports:
- port: 44134
protocol: TCP
- port: 44135
protocol: TCP
podSelector:
matchLabels:
app: helm
name: tiller
policyTypes:
- Egress
- Ingress
```
> Add network policy for tiller

- ensure_tiller_installed.go
- helmclient.go
- helmclient_test.go
- spec.go
Towards giantswarm/giantswarm#6561
First in a series of improvements to helmclient and cluster-operator to resolve this PM.
We use a port forwarding connection to talk to the Tiller API over gRPC. Now we check when we get the tiller pod that it is running.
```
k get po -n giantswarm
NAME                            READY   STATUS        RESTARTS   AGE
chart-operator-c48677b-rlbmx    1/1     Running       0          16h
tiller-deploy-86755bb48-5p6gq   0/1     Terminating   1          4h48m
tiller-deploy-86755bb48-865dw   0/1     Pending       0          4h30m
```
> When getting the tiller pod check that it is running

- ensure_tiller_installed.go
- error.go
- helmclient.go
- helmclient_test.go
- spec.go
Towards https://github.com/giantswarm/giantswarm/issues/6561
This is the other change needed. It improves the backoff handling and makes the max wait configurable. We keep the default 60 seconds for e2e tests.
> Make max wait for EnsureTillerInstalled configurable

- ensure_tiller_installed.go
Towards https://github.com/giantswarm/giantswarm/issues/6561
Aligns the backoff logic in EnsureTillerInstalled. Also fixes the returned error so operators can match on it.
> Improve error handling in EnsureTillerInstalled

- merge_values.go
- merge_values_test.go
app-operator had an issue with helmclient.MergeValues as below. 
```
E 10/01 08:20:29 /apis/application.giantswarm.io/v1alpha1/namespaces/zf3n9/apps/kubernetes-elastic-stack-elastic-logging configmapv1 stop reconciliation due to error | operatorkit/controller/controller.go:372 | controller=app-operator | event=update | loop=548 | version=141177095
/go/src/github.com/giantswarm/app-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:553:
/go/src/github.com/giantswarm/app-operator/vendor/github.com/giantswarm/operatorkit/resource/wrapper/metricsresource/crud_resource_wrapper.go:63:
/go/src/github.com/giantswarm/app-operator/vendor/github.com/giantswarm/operatorkit/resource/wrapper/retryresource/crud_resource_wrapper.go:82: …
```
> Pass nil when configmap values are empty

- ensure_tiller_installed.go
- error.go
Following https://github.com/giantswarm/app-operator/pull/161#discussion_r339672545
> Pods do have a phase but it is running not started. I'd like us to align this with the upstream terminology.
> Renaming an tiller not running error

- error.go
- pull_chart_tarball.go
Following https://github.com/giantswarm/chart-operator/pull/308#discussion_r338917401
> Is there a more specific error that we can match against? My thinking is that there is a specific case in which we really want to cancel. On the other hand there are cases which we do not expect and we should treat them like real errors.
> Return pull chart error type on when pulling failed

- ensure_tiller_installed.go
Towards giantswarm/giantswarm#7603
When testing https://github.com/giantswarm/cluster-operator/pull/787 found a problem with the fix.
Due to the backoff the TooManyResults error is not returned. Getting it straight.
> Use permanent backoff for too many tillers error

- helmclient.go
- helmclient_test.go
- spec.go
Towards https://github.com/giantswarm/giantswarm/issues/7773
In AWS China after the pause container the next image we hit on cluster creation is Tiller. So making it configurable for use in app-operator.
> Make tiller image registry configurable

- ensure_tiller_installed.go
This PR minimizes https://github.com/giantswarm/helmclient/pull/134 with stuff that can be shipped independently from 1.16 upgrade, like the migration of long time deprecated API groups which are being dropped in 1.16.
> Migrate PSP API group use from deprecated extensions to policy

- pull_chart_tarball.go
This is to try and fix the 404 errors we've been seeing pulling chart tarballs. These eventually clear but it takes a long time and is super annoying.
@TheoBrigitte was able to repro with curl by setting an empty host header. So this sets the header once we've created the request.
See https://gigantic.slack.com/archives/C76JX6YLQ/p1576590423053600
> Set host header to prevent 404 errors from GitHub pages

- ensure_tiller_installed.go
Towards https://github.com/giantswarm/giantswarm/issues/8190
We will configure the max wait to 30 secs instead of 2 mins in app-operator. But I couple of the retries missed this setting.
> Use configured backoff time in EnsureTillerInstalled

- .circleci/config.yml
- error.go
- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/7355
Handles additional error cases. Used in https://github.com/giantswarm/chart-operator/pull/343.
- Chart tarball has an empty templates directory.
- Helm release name is invalid.
- Helm release is not deployed.
> Handle additional errors

- error.go
- pull_chart_tarball.go
Towards https://github.com/giantswarm/giantswarm/issues/8573
Adds missing monitoring to PullChartTarball and handles timeout errors which we see sometimes in multiple installations.
> Handle timeouts pulling charts and add monitoring

- pull_chart_tarball.go
Towards https://github.com/giantswarm/giantswarm/issues/9079
Currently we return a permanent error if we hit a timout. So we don't use the retry logic.
This is dumb since the retry might succeed. We still cancel the resource in chart-operator if there is a timeout after the retries.
> Retry if pulling chart tarball fails

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/giantswarm/k8sclient/Gopkg.lock
- vendor/github.com/giantswarm/k8sclient/Gopkg.toml
- vendor/github.com/giantswarm/k8sclient/k8scrdclient/k8scrdclient.go
- vendor/github.com/giantswarm/micrologger/CHANGELOG.md
We need to pin the micrologger dependency to the v0.1.0 version which is the one using dep instead of newer versions that use go modules.
> Use micrologger v0.1.0

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/giantswarm/errors/tenant/error.go
- vendor/github.com/giantswarm/k8sclient/Gopkg.lock
- vendor/github.com/giantswarm/k8sclient/Gopkg.toml
- vendor/github.com/giantswarm/k8sportforward/Gopkg.lock
- vendor/github.com/giantswarm/k8sportforward/Gopkg.toml
- vendor/github.com/giantswarm/microerror/CHANGELOG.md
- vendor/github.com/giantswarm/micrologger/CHANGELOG.md
- vendor/github.com/giantswarm/micrologger/Gopkg.lock
- vendor/github.com/giantswarm/micrologger/Gopkg.toml
We need to pin the microerror and micrologger dependencies to the v0.1.0 version to avoid getting breaking changes.
> Pin dependencies

- helmclient.go
Towards https://github.com/giantswarm/giantswarm/issues/9246
We check `IsTarballNotFound` on install but not on update. We should check in both cases. As there is no point retrying if the tarball does not exist.
> Handle missing tarballs when updating releases

- spec.go
Towards giantswarm/roadmap#30
The Helm release statuses change with Helm 3. In chart-operator the strings are hardcoded in lots of places.
This adds them as constants here. The rationale is so we can have constants but without importing helm packages.
> helm3:  Add constants for statuses

- CHANGELOG.md
- pull_chart_tarball.go
Towards https://github.com/giantswarm/giantswarm/issues/9946
We should handle 503 errors from GitHub Pages. chart-operator will then cancel the release resource and retry correctly.
> Handle 503 errors when pulling chart tarballs fails

- CHANGELOG.md
- helmclient.go
- spec.go
Towards https://github.com/giantswarm/giantswarm/issues/9946
We currently use a hardcoded HTTP client timeout of 5 secs when pulling chart tarballs. This is regularly timing out in AWS China due to the slow network. 
This makes it configurable so it can be increased in these installations.
> Increase HTTP client timeout from 5 to 30 secs for testing

- helmclient.go
- pull_chart_tarball.go
- spec.go
Syncing helm3 branch with master.
- Handle 503s when GitHub Pages is unavailable https://github.com/giantswarm/helmclient/pull/196
- Make HTTP client timeout configurable so it can be increased in AWS China. https://github.com/giantswarm/helmclient/pull/198
> Helm3 error handling

- CHANGELOG.md
- error.go
Toward https://github.com/giantswarm/giantswarm/issues/11167
To support the below error message from helm 3, we are adding a new error matcher function. 
```
unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in PodSecurityPolicy.metadata.labels.app
```
> Add manifest error

- CHANGELOG.md
- error.go
Toward https://github.com/giantswarm/giantswarm/issues/11260
To my surprise, `helm install` & `helm upgrade` have a different logging message when same validation has a problem. 
this PR introduces `validationFailedError` which checks the same words for both validation error cases.
> Add validationFailedError

- CHANGELOG.md
- error.go
- merge_values.go
- merge_values_test.go
Toward https://github.com/giantswarm/giantswarm/issues/11469
I will use new errors in chart-operator, to let users know they have a problem in their configmap/secret.
> Extending map merging errors

- helmclient.go
- helmclient_test.go
- types.go
Toward https://github.com/giantswarm/giantswarm/issues/11651
There's no way to extract release namespace information from any other resources. 
Hence I'm back to change the spec of helmclient for 0.x.x.
> Exposing Release namespace 

- CHANGELOG.md
- helmclienttest/helmclient.go
- integration/test/basic/basic_test.go
- rollback.go
- spec.go
Towards https://github.com/giantswarm/giantswarm/issues/12245
Currently `helm upgrade --force` is unusable for us as it doesn't recreate resources it just disables the 3 way merge. Without recreate support Helm errors when updating immutable fields.
So this is prep for implementing automated rollback support in chart-operator.
> Add rollback support

- CHANGELOG.md
- pkg/helmclient/pull_chart_tarball.go
If a request is made and 404 is initially returned, make sure that subsequent
requests revalidate the cached entry (preventing 404 when asset exists)
fix giantswam/giantswarm#9747
> Revalidate the cached request

- go.mod
This is to [fix the CVE](https://github.com/containerd/containerd/releases/tag/v1.6.12) I stumbled upon when building Chart Operator.
> Updating modules
